
CREATE DATABASE senai_Pizzarias_extra

USE SENAI_PIZZARIAS_EXTRA

CREATE TABLE USUARIO(
 ID INT IDENTITY PRIMARY KEY
 , EMAIL VARCHAR(250) UNIQUE NOT NULL
 , SENHA VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE PIZZARIAS (
 ID INT IDENTITY PRIMARY KEY
 ,NOME VARCHAR(250) NOT NULL
 ,ISVEGAN BIT NOT NULL
 ,CATEGORIA INT NOT NULL
 ,ENDERECO VARCHAR(250) NOT NULL
 ,TELEFONE_COMERCIAL VARCHAR(250) NOT NULL
);



